export const BILLING_EVENTS = [
  'APP_INSTALLS',
  'CLICKS',
  'IMPRESSIONS',
  'LINK_CLICKS',
  'NONE',
  'OFFER_CLAIMS',
  'PAGE_LIKES',
  'POST_ENGAGEMENT',
  'THRUPLAY',
  'PURCHASE',
  'LISTING_INTERACTION',
];
