import {
    ShoppingBag,
    Utensils,
    Dumbbell,
    Camera,
    Coffee,
    Briefcase,
    Heart,
    Car,
    Home,
    Palette,
    Music,
    BookOpen,
    Plane
} from "lucide-react"

export const businessTypes = [
    { id: "ecommerce", name: "E-commerce", icon: ShoppingBag, color: "bg-blue-500" },
    { id: "restaurant", name: "Restaurant", icon: Utensils, color: "bg-green-500" },
    { id: "fitness", name: "Fitness & Gym", icon: Dumbbell, color: "bg-purple-500" },
    { id: "photography", name: "Photography", icon: Camera, color: "bg-pink-500" },
    { id: "coffee", name: "Coffee Shop", icon: Coffee, color: "bg-orange-500" },
    { id: "consulting", name: "Consulting", icon: Briefcase, color: "bg-indigo-500" },
    { id: "healthcare", name: "Healthcare", icon: Heart, color: "bg-red-500" },
    { id: "automotive", name: "Automotive", icon: Car, color: "bg-gray-500" },
    { id: "realestate", name: "Real Estate", icon: Home, color: "bg-emerald-500" },
    { id: "creative", name: "Creative Services", icon: Palette, color: "bg-yellow-500" },
    { id: "entertainment", name: "Entertainment", icon: Music, color: "bg-violet-500" },
    { id: "education", name: "Education", icon: BookOpen, color: "bg-cyan-500" },
    { id: "travel", name: "Travel & Tourism", icon: Plane, color: "bg-teal-500" },
    { id: "it", name: "IT & Software", icon: Briefcase, color: "bg-blue-800" },
    { id: "marketing", name: "Marketing Agency", icon: Briefcase, color: "bg-pink-600" },
    { id: "finance", name: "Finance & Accounting", icon: Briefcase, color: "bg-green-800" },
    { id: "legal", name: "Legal Services", icon: Briefcase, color: "bg-gray-700" },
    { id: "logistics", name: "Logistics & Transport", icon: Car, color: "bg-yellow-800" },
    { id: "manufacturing", name: "Manufacturing", icon: Briefcase, color: "bg-orange-700" },
    { id: "retail", name: "Retail Store", icon: ShoppingBag, color: "bg-lime-600" },
    { id: "beauty", name: "Beauty & Salon", icon: Palette, color: "bg-pink-400" },
    { id: "nonprofit", name: "Non-Profit", icon: Heart, color: "bg-rose-500" },
    { id: "events", name: "Events & Weddings", icon: Music, color: "bg-fuchsia-500" },
    { id: "construction", name: "Construction", icon: Home, color: "bg-yellow-700" },
    { id: "agriculture", name: "Agriculture", icon: Home, color: "bg-green-700" },
    { id: "media", name: "Media & Publishing", icon: BookOpen, color: "bg-indigo-700" },
    { id: "other", name: "Other", icon: Briefcase, color: "bg-gray-400" },
]

export const budgetRanges = [
    { id: "small", label: "₹8,000 - ₹40,000/month", description: "Perfect for small local businesses" },
    { id: "medium", label: "₹40,000 - ₹1,60,000/month", description: "Great for growing businesses" },
    { id: "large", label: "₹1,60,000 - ₹8,00,000/month", description: "Ideal for established companies" },
    { id: "enterprise", label: "₹8,00,000+/month", description: "For large enterprises and agencies" },
]

export const goals = [
    { id: "awareness", name: "Brand Awareness", description: "Get your business known in your area" },
    { id: "leads", name: "Generate Leads", description: "Collect contact information from potential customers" },
    { id: "sales", name: "Drive Sales", description: "Increase direct sales and revenue" },
    { id: "traffic", name: "Website Traffic", description: "Bring more visitors to your website" },
    { id: "engagement", name: "Social Engagement", description: "Build a community around your brand" },
    { id: "app", name: "App Downloads", description: "Promote your mobile application" },
    { id: "retention", name: "Customer Retention", description: "Keep your customers coming back" },
    { id: "reviews", name: "Get Reviews", description: "Encourage customers to leave positive reviews" },
    { id: "subscriptions", name: "Increase Subscriptions", description: "Grow your subscriber base" },
    { id: "bookings", name: "Increase Bookings", description: "Get more appointments or reservations" },
    { id: "community", name: "Community Building", description: "Foster a loyal community around your brand" },
    { id: "education", name: "Educate Audience", description: "Share knowledge and expertise" },
    { id: "donations", name: "Increase Donations", description: "Raise more funds for your cause" },
    { id: "awards", name: "Win Awards", description: "Get recognized for your work" },
    { id: "partnerships", name: "Build Partnerships", description: "Collaborate with other businesses" },
    { id: "brandloyalty", name: "Brand Loyalty", description: "Turn customers into advocates" },
    { id: "marketshare", name: "Increase Market Share", description: "Expand your business reach" },
    { id: "international", name: "International Expansion", description: "Grow your business globally" },
    { id: "other", name: "Other", description: "Custom or unique business goals" },
]
