// Facebook Marketing API Billing Events
const BILLING_EVENTS = [
  'APP_INSTALLS',
  'CLICKS',
  'IMPRESSIONS',
  'LINK_CLICKS',
  'NONE',
  'OFFER_CLAIMS',
  'PAGE_LIKES',
  'POST_ENGAGEMENT',
  'VIDEO_VIEWS',
  'THRUPLAY',
  'PURCHASE',
  'LISTING_INTERACTION',
  'COMPLETE_REGISTRATION',
  'CONTACT',
  'CUSTOMIZE_PRODUCT',
  'DONATE',
  'FIND_LOCATION',
  'SCHEDULE',
  'START_TRIAL',
  'SUBMIT_APPLICATION',
  'SUBSCRIBE',
  'ADD_TO_CART',
  'ADD_TO_WISHLIST',
  'INITIATED_CHECKOUT',
  'ADD_PAYMENT_INFO',
  'LEAD',
  'SEARCH'
];

module.exports = { BILLING_EVENTS };
