export interface CreateCreativeRequest {
  name: string;
  // Object Story Creative
  object_story_id?: string;
  // Link Creative
  object_story_spec?: {
    page_id?: string;
    link_data?: {
      call_to_action?: {
        type: string;
        value?: {
          link?: string;
          application?: string;
        };
      };
      description?: string;
      image_hash?: string;
      image_url?: string;
      link?: string;
      message?: string;
      name?: string;
      video_id?: string;
    };
    video_data?: {
      call_to_action?: {
        type: string;
        value?: {
          link?: string;
          application?: string;
        };
      };
      description?: string;
      image_hash?: string;
      image_url?: string;
      message?: string;
      title?: string;
      video_id?: string;
    };
    photo_data?: {
      call_to_action?: {
        type: string;
        value?: {
          link?: string;
        };
      };
      description?: string;
      image_hash?: string;
      image_url?: string;
      message?: string;
      name?: string;
      url?: string;
    };
  };
  // Asset Feed Spec
  asset_feed_spec?: {
    ad_formats?: string[];
    call_to_action_types?: string[];
    link_urls?: Array<{
      website_url: string;
      display_url?: string;
    }>;
    descriptions?: string[];
    headlines?: string[];
    images?: Array<{
      hash: string;
      url?: string;
    }>;
    videos?: Array<{
      video_id: string;
      thumbnail_url?: string;
    }>;
    bodies?: string[];
    optimization_type?: string;
    carousels?: Array<{
      link_url: string;
      headline: string;
      description?: string;
      image_hash?: string;
      image_url?: string;
      video_id?: string;
    }>;
  };
  // Template-based Creative
  template_url?: string;
  url_tags?: string;
  // Degrees of Freedom Spec
  degrees_of_freedom_spec?: {
    creative_features_spec?: {
      standard_enhancements?: {
        enhancements_catalog?: {
          image_enhancement_catalog?: {
            brightness?: number;
            contrast?: number;
            saturation?: number;
          };
          video_enhancement_catalog?: {
            brightness?: number;
            contrast?: number;
          };
        };
      };
    };
  };
  // Status
  status?: 'ACTIVE' | 'PAUSED' | 'DELETED' | 'PENDING_REVIEW' | 'DISAPPROVED' | 'PREAPPROVED';
  // Additional fields
  adlabels?: Array<{
    id: string;
    name: string;
  }>;
  applink_treatment?: 'deeplink_with_web_fallback' | 'deeplink_with_appstore_fallback' | 'web_only';
  authorization_category?: string;
  auto_update?: boolean;
  branded_content_sponsor_page_id?: string;
  bundle_folder_id?: string;
  call_to_action_type?: string;
  categorization_criteria?: string;
  category_media_source?: string;
  destination_set_id?: string;
  dynamic_ad_voice?: string;
  effective_authorization_category?: string;
  effective_instagram_media_id?: string;
  effective_instagram_story_id?: string;
  enable_direct_install?: boolean;
  enable_launch_instant_app?: boolean;
  image_crops?: any;
  image_hash?: string;
  image_url?: string;
  instagram_actor_id?: string;
  instagram_permalink_url?: string;
  instagram_story_id?: string;
  instagram_user_id?: string;
  interactive_components_spec?: any;
  link_deep_link_url?: string;
  link_destination_display_url?: string;
  link_og_id?: string;
  link_url?: string;
  messenger_sponsored_message?: string;
  modal_dialog?: boolean;
  place_page_set_id?: string;
  platform_customizations?: any;
  playable_asset_id?: string;
  portrait_customizations?: any;
  product_set_id?: string;
  recommender_settings?: any;
  source_instagram_media_id?: string;
  thumbnail_url?: string;
  title?: string;
  use_page_actor_override?: boolean;
  video_id?: string;
}

export interface UpdateCreativeRequest {
  name?: string;
  status?: 'ACTIVE' | 'PAUSED' | 'DELETED' | 'PENDING_REVIEW' | 'DISAPPROVED' | 'PREAPPROVED';
  adlabels?: Array<{
    id: string;
    name: string;
  }>;
  authorization_category?: string;
  categorization_criteria?: string;
  run_status?: 'ACTIVE' | 'PAUSED' | 'DELETED' | 'PENDING_REVIEW' | 'DISAPPROVED' | 'PREAPPROVED';
  // Limited fields that can be updated
}

export interface CreativeResponse {
  id: string;
  name: string;
  object_story_id?: string;
  object_story_spec?: any;
  asset_feed_spec?: any;
  template_url?: string;
  url_tags?: string;
  degrees_of_freedom_spec?: any;
  status: string;
  adlabels?: Array<{
    id: string;
    name: string;
  }>;
  applink_treatment?: string;
  authorization_category?: string;
  auto_update?: boolean;
  branded_content_sponsor_page_id?: string;
  bundle_folder_id?: string;
  call_to_action_type?: string;
  categorization_criteria?: string;
  category_media_source?: string;
  destination_set_id?: string;
  dynamic_ad_voice?: string;
  effective_authorization_category?: string;
  effective_instagram_media_id?: string;
  effective_instagram_story_id?: string;
  enable_direct_install?: boolean;
  enable_launch_instant_app?: boolean;
  image_crops?: any;
  image_hash?: string;
  image_url?: string;
  instagram_actor_id?: string;
  instagram_permalink_url?: string;
  instagram_story_id?: string;
  instagram_user_id?: string;
  interactive_components_spec?: any;
  link_deep_link_url?: string;
  link_destination_display_url?: string;
  link_og_id?: string;
  link_url?: string;
  messenger_sponsored_message?: string;
  modal_dialog?: boolean;
  place_page_set_id?: string;
  platform_customizations?: any;
  playable_asset_id?: string;
  portrait_customizations?: any;
  product_set_id?: string;
  recommender_settings?: any;
  source_instagram_media_id?: string;
  thumbnail_url?: string;
  title?: string;
  use_page_actor_override?: boolean;
  video_id?: string;
  // Note: updated_time is not available for AdCreative objects in Facebook API
}

export interface CreativePreviewRequest {
  creative_id?: string;
  creative_spec?: CreateCreativeRequest;
  ad_format: 'DESKTOP_FEED_STANDARD' | 'MOBILE_FEED_STANDARD' | 'RIGHT_COLUMN_STANDARD' | 'MOBILE_FULLWIDTH' | 'MOBILE_NATIVE' | 'DESKTOP_SIDEBAR_STANDARD' | 'MOBILE_MEDIUM_RECTANGLE' | 'MOBILE_BANNER' | 'DESKTOP_FEED_STANDARD_CAROUSEL' | 'MOBILE_FEED_STANDARD_CAROUSEL' | 'INSTAGRAM_STANDARD' | 'INSTAGRAM_STORY' | 'MESSENGER_MOBILE_INBOX_MEDIA' | 'MESSENGER_MOBILE_STORY_MEDIA' | 'MESSENGER_DESKTOP_INBOX_MEDIA' | 'MESSENGER_MOBILE_INBOX_MEDIA_RICH' | 'MESSENGER_MOBILE_STORY_MEDIA_RICH' | 'MESSENGER_DESKTOP_INBOX_MEDIA_RICH' | 'AUDIENCE_NETWORK_OUTSTREAM_VIDEO' | 'AUDIENCE_NETWORK_BANNER' | 'AUDIENCE_NETWORK_INTERSTITIAL' | 'AUDIENCE_NETWORK_NATIVE' | 'AUDIENCE_NETWORK_NATIVE_BANNER' | 'AUDIENCE_NETWORK_REWARDED_VIDEO' | 'AUDIENCE_NETWORK_INSTREAM_VIDEO' | 'INSTANT_ARTICLE_STANDARD' | 'INSTANT_ARTICLE_RECIRCULATION_AD' | 'INSTREAM_VIDEO_DESKTOP' | 'INSTREAM_VIDEO_MOBILE' | 'SUGGESTED_VIDEO_DESKTOP' | 'SUGGESTED_VIDEO_MOBILE' | 'MARKETPLACE_MOBILE' | 'FACEBOOK_STORY_MOBILE' | 'FACEBOOK_STORY_STICKER_MOBILE' | 'FACEBOOK_FEED_DESKTOP' | 'FACEBOOK_FEED_MOBILE' | 'FACEBOOK_RIGHT_COLUMN_DESKTOP' | 'FACEBOOK_MARKETPLACE_MOBILE' | 'FACEBOOK_VIDEO_FEEDS_MOBILE' | 'FACEBOOK_VIDEO_FEEDS_DESKTOP' | 'FACEBOOK_STORY_DESKTOP' | 'FACEBOOK_SEARCH_RESULTS_DESKTOP' | 'FACEBOOK_SEARCH_RESULTS_MOBILE' | 'FACEBOOK_GROUPS_FEED_DESKTOP' | 'FACEBOOK_GROUPS_FEED_MOBILE' | 'FACEBOOK_BUSINESS_DISCOVERY_MOBILE' | 'FACEBOOK_REELS_MOBILE' | 'FACEBOOK_REELS_DESKTOP' | 'WATCH_FEED_MOBILE' | 'WATCH_FEED_DESKTOP' | 'INSTAGRAM_STANDARD_CAROUSEL' | 'INSTAGRAM_STORY_CAROUSEL' | 'INSTAGRAM_REELS' | 'INSTAGRAM_EXPLORE' | 'INSTAGRAM_EXPLORE_GRID_HOME' | 'INSTAGRAM_EXPLORE_CONTEXTUAL' | 'INSTAGRAM_REELS_OVERLAY' | 'INSTAGRAM_SEARCH_RESULTS' | 'INSTAGRAM_PROFILE_REELS' | 'INSTAGRAM_PROFILE_FEED' | 'INSTAGRAM_SHOP' | 'THREADS_MOBILE' | 'THREADS_DESKTOP';
  product_item_ids?: string[];
  place_page_id?: string;
  post_id?: string;
  end_date?: string;
  start_date?: string;
  interactive_components_spec?: any;
  locale?: string;
  dynamic_creative_spec?: any;
  dynamic_asset_spec?: any;
}

export interface CreativePreviewResponse {
  body: string; // HTML content for the preview
}

export interface CreativeInsightsRequest {
  time_range?: {
    since: string;
    until: string;
  };
  date_preset?: 'today' | 'yesterday' | 'this_month' | 'last_month' | 'this_quarter' | 'maximum' | 'data_maximum' | 'last_3d' | 'last_7d' | 'last_14d' | 'last_28d' | 'last_30d' | 'last_90d' | 'last_week_mon_sun' | 'last_week_sun_sat' | 'last_quarter' | 'last_year' | 'this_week_mon_today' | 'this_week_sun_today' | 'this_year';
  fields?: string[];
  filtering?: Array<{
    field: string;
    operator: string;
    value: string | number | string[];
  }>;
  breakdowns?: string[];
  sort?: string[];
  level?: 'account' | 'campaign' | 'adset' | 'ad' | 'creative';
  limit?: number;
  after?: string;
  before?: string;
}

export interface CreativeInsightsResponse {
  data: Array<{
    date_start: string;
    date_stop: string;
    impressions?: string;
    clicks?: string;
    spend?: string;
    ctr?: string;
    cpc?: string;
    cpm?: string;
    cpp?: string;
    reach?: string;
    frequency?: string;
    actions?: Array<{
      action_type: string;
      value: string;
    }>;
    cost_per_action_type?: Array<{
      action_type: string;
      value: string;
    }>;
    video_avg_time_watched_actions?: Array<{
      action_type: string;
      value: string;
    }>;
    video_p25_watched_actions?: Array<{
      action_type: string;
      value: string;
    }>;
    video_p50_watched_actions?: Array<{
      action_type: string;
      value: string;
    }>;
    video_p75_watched_actions?: Array<{
      action_type: string;
      value: string;
    }>;
    video_p100_watched_actions?: Array<{
      action_type: string;
      value: string;
    }>;
    [key: string]: any;
  }>;
  paging?: {
    cursors?: {
      before?: string;
      after?: string;
    };
    next?: string;
    previous?: string;
  };
}

// Call to Action Types
export const CALL_TO_ACTION_TYPES = [
  'OPEN_LINK',
  'LIKE_PAGE',
  'SHOP_NOW',
  'PLAY_GAME',
  'INSTALL_APP',
  'USE_APP',
  'INSTALL_MOBILE_APP',
  'USE_MOBILE_APP',
  'BOOK_TRAVEL',
  'LISTEN_MUSIC',
  'WATCH_VIDEO',
  'LEARN_MORE',
  'SIGN_UP',
  'DOWNLOAD',
  'WATCH_MORE',
  'NO_BUTTON',
  'VISIT_PAGES_FEED',
  'APPLY_NOW',
  'BUY_NOW',
  'CONTACT_US',
  'DONATE',
  'SUBSCRIBE',
  'SAY_THANKS',
  'SELL_NOW',
  'SHARE',
  'DONATE_NOW',
  'GET_OFFER',
  'GET_OFFER_VIEW',
  'BUY_TICKETS',
  'UPDATE_APP',
  'GET_DIRECTIONS',
  'BUY',
  'MESSAGE_PAGE',
  'MOBILE_DOWNLOAD',
  'SAVE',
  'CONTINUE',
  'CALL',
  'CALL_ME',
  'START_ORDER',
  'CONTINUE_SHOPPING',
  'SEND_MESSAGE',
  'SEND_EMAIL',
  'SEND_SMS',
  'WHATSAPP_MESSAGE',
  'FOLLOW_NEWS_STORYLINE',
  'FOLLOW_USER',
  'FOLLOW_PAGE',
  'RAISE_MONEY',
  'VOTE',
  'REGISTER',
  'REQUEST_TIME',
  'SEE_MORE',
  'TRY_IT',
  'JOIN_CHANNEL',
  'LOYALTY_LEARN_MORE',
  'PURCHASE_GIFT_CARDS',
  'PAY_TO_ACCESS',
  'MISSED_CALL',
  'AUDIO_CALL',
  'VIDEO_CALL',
  'MOBILE_CENTRE',
  'MOBILE_SHOP',
  'MOBILE_BOOK',
  'MOBILE_CONTACT',
  'MOBILE_DOWNLOAD_ON_DEMAND',
  'MOBILE_INSTALL',
  'MOBILE_LEARN_MORE',
  'MOBILE_LISTEN',
  'MOBILE_OPEN_CANVAS',
  'MOBILE_SEARCH',
  'MOBILE_SIGN_UP',
  'MOBILE_VISIT_STORE',
  'MOBILE_WATCH',
  'MOBILE_PLAY',
  'MOBILE_MESSAGE',
  'MOBILE_CALL',
  'MOBILE_CALL_NOW',
  'MOBILE_DIRECTIONS',
  'MOBILE_EVENT_RSVP',
  'MOBILE_FIND_STORE',
  'MOBILE_FOLLOW',
  'MOBILE_GET_OFFER',
  'MOBILE_LIKE',
  'MOBILE_SEND',
  'MOBILE_SHARE',
  'MOBILE_SUBSCRIBE',
  'MOBILE_OPEN_COLLECTION',
  'MOBILE_SEND_INVITATION',
  'MOBILE_EMAIL',
  'MOBILE_FOLLOW_INSTAGRAM',
  'MOBILE_FOLLOW_FACEBOOK',
  'MOBILE_FOLLOW_TWITTER',
  'MOBILE_FOLLOW_YOUTUBE',
  'MOBILE_FOLLOW_MESSENGER',
  'MOBILE_FOLLOW_LINKEDIN',
  'MOBILE_FOLLOW_PINTEREST',
  'MOBILE_FOLLOW_SNAPCHAT',
  'MOBILE_FOLLOW_TIKTOK',
  'MOBILE_FOLLOW_TWITCH',
  'MOBILE_FOLLOW_WHATSAPP',
  'MOBILE_FOLLOW_TELEGRAM',
  'MOBILE_FOLLOW_DISCORD',
  'MOBILE_FOLLOW_REDDIT',
  'MOBILE_FOLLOW_TUMBLR',
  'MOBILE_FOLLOW_WECHAT',
  'MOBILE_FOLLOW_CLUBHOUSE',
  'MOBILE_FOLLOW_SIGNAL',
  'MOBILE_FOLLOW_VIBER',
  'MOBILE_FOLLOW_KAKAO',
  'MOBILE_FOLLOW_LINE',
  'MOBILE_FOLLOW_SKYPE',
  'MOBILE_FOLLOW_ZOOM',
  'MOBILE_FOLLOW_TEAMS',
  'MOBILE_FOLLOW_SLACK',
  'MOBILE_FOLLOW_BANDCAMP',
  'MOBILE_FOLLOW_SOUNDCLOUD',
  'MOBILE_FOLLOW_SPOTIFY',
  'MOBILE_FOLLOW_APPLE_MUSIC',
  'MOBILE_FOLLOW_GOOGLE_PODCASTS',
  'MOBILE_FOLLOW_ANCHOR',
  'MOBILE_FOLLOW_PODCAST',
  'MOBILE_FOLLOW_NEWSLETTER',
  'MOBILE_FOLLOW_BLOG',
  'MOBILE_FOLLOW_WEBSITE',
  'MOBILE_FOLLOW_RSS',
  'MOBILE_FOLLOW_FORUM',
  'MOBILE_FOLLOW_COMMUNITY',
  'MOBILE_FOLLOW_GROUP',
  'MOBILE_FOLLOW_MEETUP',
  'MOBILE_FOLLOW_EVENT',
  'MOBILE_FOLLOW_CAMPAIGN',
  'MOBILE_FOLLOW_CAUSE',
  'MOBILE_FOLLOW_PETITION',
  'MOBILE_FOLLOW_FUNDRAISER',
  'MOBILE_FOLLOW_CHARITY',
  'MOBILE_FOLLOW_ORGANIZATION',
  'MOBILE_FOLLOW_BUSINESS',
  'MOBILE_FOLLOW_BRAND',
  'MOBILE_FOLLOW_PRODUCT',
  'MOBILE_FOLLOW_SERVICE',
  'MOBILE_FOLLOW_OFFER',
  'MOBILE_FOLLOW_DEAL',
  'MOBILE_FOLLOW_COUPON',
  'MOBILE_FOLLOW_DISCOUNT',
  'MOBILE_FOLLOW_SALE',
  'MOBILE_FOLLOW_PROMOTION',
  'MOBILE_FOLLOW_CONTEST',
  'MOBILE_FOLLOW_GIVEAWAY',
  'MOBILE_FOLLOW_SWEEPSTAKES',
  'MOBILE_FOLLOW_LOTTERY',
  'MOBILE_FOLLOW_RAFFLE',
  'MOBILE_FOLLOW_AUCTION',
  'MOBILE_FOLLOW_MARKETPLACE',
  'MOBILE_FOLLOW_STORE',
  'MOBILE_FOLLOW_SHOP',
  'MOBILE_FOLLOW_MALL',
  'MOBILE_FOLLOW_OUTLET',
  'MOBILE_FOLLOW_CATALOG',
  'MOBILE_FOLLOW_INVENTORY',
  'MOBILE_FOLLOW_STOCK',
  'MOBILE_FOLLOW_SUPPLY',
  'MOBILE_FOLLOW_DEMAND',
  'MOBILE_FOLLOW_ORDER',
  'MOBILE_FOLLOW_PURCHASE',
  'MOBILE_FOLLOW_PAYMENT',
  'MOBILE_FOLLOW_INVOICE',
  'MOBILE_FOLLOW_RECEIPT',
  'MOBILE_FOLLOW_REFUND',
  'MOBILE_FOLLOW_RETURN',
  'MOBILE_FOLLOW_EXCHANGE',
  'MOBILE_FOLLOW_WARRANTY',
  'MOBILE_FOLLOW_GUARANTEE',
  'MOBILE_FOLLOW_INSURANCE',
  'MOBILE_FOLLOW_COVERAGE',
  'MOBILE_FOLLOW_PROTECTION',
  'MOBILE_FOLLOW_SECURITY',
  'MOBILE_FOLLOW_PRIVACY',
  'MOBILE_FOLLOW_SAFETY',
  'MOBILE_FOLLOW_HEALTH',
  'MOBILE_FOLLOW_WELLNESS',
  'MOBILE_FOLLOW_FITNESS',
  'MOBILE_FOLLOW_NUTRITION',
  'MOBILE_FOLLOW_DIET',
  'MOBILE_FOLLOW_RECIPE',
  'MOBILE_FOLLOW_COOKING',
  'MOBILE_FOLLOW_FOOD',
  'MOBILE_FOLLOW_RESTAURANT',
  'MOBILE_FOLLOW_DELIVERY',
  'MOBILE_FOLLOW_TAKEOUT',
  'MOBILE_FOLLOW_PICKUP',
  'MOBILE_FOLLOW_CATERING',
  'MOBILE_FOLLOW_RESERVATION',
  'MOBILE_FOLLOW_BOOKING',
  'MOBILE_FOLLOW_APPOINTMENT',
  'MOBILE_FOLLOW_SCHEDULE',
  'MOBILE_FOLLOW_CALENDAR',
  'MOBILE_FOLLOW_REMINDER',
  'MOBILE_FOLLOW_NOTIFICATION',
  'MOBILE_FOLLOW_ALERT',
  'MOBILE_FOLLOW_UPDATE',
  'MOBILE_FOLLOW_NEWS',
  'MOBILE_FOLLOW_REPORT',
  'MOBILE_FOLLOW_ARTICLE',
  'MOBILE_FOLLOW_STORY',
  'MOBILE_FOLLOW_POST',
  'MOBILE_FOLLOW_CONTENT',
  'MOBILE_FOLLOW_MEDIA',
  'MOBILE_FOLLOW_VIDEO',
  'MOBILE_FOLLOW_AUDIO',
  'MOBILE_FOLLOW_PHOTO',
  'MOBILE_FOLLOW_IMAGE',
  'MOBILE_FOLLOW_GRAPHIC',
  'MOBILE_FOLLOW_DESIGN',
  'MOBILE_FOLLOW_ART',
  'MOBILE_FOLLOW_CRAFT',
  'MOBILE_FOLLOW_DIY',
  'MOBILE_FOLLOW_TUTORIAL',
  'MOBILE_FOLLOW_GUIDE',
  'MOBILE_FOLLOW_MANUAL',
  'MOBILE_FOLLOW_INSTRUCTION',
  'MOBILE_FOLLOW_DEMO',
  'MOBILE_FOLLOW_EXAMPLE',
  'MOBILE_FOLLOW_SAMPLE',
  'MOBILE_FOLLOW_TEMPLATE',
  'MOBILE_FOLLOW_PATTERN',
  'MOBILE_FOLLOW_MODEL',
  'MOBILE_FOLLOW_FRAMEWORK',
  'MOBILE_FOLLOW_STRUCTURE',
  'MOBILE_FOLLOW_SYSTEM',
  'MOBILE_FOLLOW_PROCESS',
  'MOBILE_FOLLOW_WORKFLOW',
  'MOBILE_FOLLOW_PROCEDURE',
  'MOBILE_FOLLOW_METHOD',
  'MOBILE_FOLLOW_TECHNIQUE',
  'MOBILE_FOLLOW_STRATEGY',
  'MOBILE_FOLLOW_PLAN',
  'MOBILE_FOLLOW_GOAL',
  'MOBILE_FOLLOW_TARGET',
  'MOBILE_FOLLOW_OBJECTIVE',
  'MOBILE_FOLLOW_MISSION',
  'MOBILE_FOLLOW_VISION',
  'MOBILE_FOLLOW_PURPOSE',
  'MOBILE_FOLLOW_MEANING',
  'MOBILE_FOLLOW_VALUE',
  'MOBILE_FOLLOW_BENEFIT',
  'MOBILE_FOLLOW_ADVANTAGE',
  'MOBILE_FOLLOW_FEATURE',
  'MOBILE_FOLLOW_FUNCTION',
  'MOBILE_FOLLOW_CAPABILITY',
  'MOBILE_FOLLOW_SKILL',
  'MOBILE_FOLLOW_TALENT',
  'MOBILE_FOLLOW_ABILITY',
  'MOBILE_FOLLOW_EXPERTISE',
  'MOBILE_FOLLOW_KNOWLEDGE',
  'MOBILE_FOLLOW_EXPERIENCE',
  'MOBILE_FOLLOW_BACKGROUND',
  'MOBILE_FOLLOW_HISTORY',
  'MOBILE_FOLLOW_STORY',
  'MOBILE_FOLLOW_BIOGRAPHY',
  'MOBILE_FOLLOW_PROFILE',
  'MOBILE_FOLLOW_PORTFOLIO',
  'MOBILE_FOLLOW_RESUME',
  'MOBILE_FOLLOW_CV',
  'MOBILE_FOLLOW_CREDENTIALS',
  'MOBILE_FOLLOW_QUALIFICATIONS',
  'MOBILE_FOLLOW_CERTIFICATIONS',
  'MOBILE_FOLLOW_LICENSES',
  'MOBILE_FOLLOW_PERMITS',
  'MOBILE_FOLLOW_AUTHORIZATION',
  'MOBILE_FOLLOW_APPROVAL',
  'MOBILE_FOLLOW_PERMISSION',
  'MOBILE_FOLLOW_ACCESS',
  'MOBILE_FOLLOW_ENTRY',
  'MOBILE_FOLLOW_MEMBERSHIP',
  'MOBILE_FOLLOW_SUBSCRIPTION',
  'MOBILE_FOLLOW_REGISTRATION',
  'MOBILE_FOLLOW_SIGNUP',
  'MOBILE_FOLLOW_LOGIN',
  'MOBILE_FOLLOW_ACCOUNT',
  'MOBILE_FOLLOW_PROFILE',
  'MOBILE_FOLLOW_DASHBOARD',
  'MOBILE_FOLLOW_SETTINGS',
  'MOBILE_FOLLOW_PREFERENCES',
  'MOBILE_FOLLOW_OPTIONS',
  'MOBILE_FOLLOW_CHOICES',
  'MOBILE_FOLLOW_SELECTION',
  'MOBILE_FOLLOW_DECISION',
  'MOBILE_FOLLOW_CHOICE',
  'MOBILE_FOLLOW_OPTION',
  'MOBILE_FOLLOW_ALTERNATIVE',
  'MOBILE_FOLLOW_SOLUTION',
  'MOBILE_FOLLOW_ANSWER',
  'MOBILE_FOLLOW_RESPONSE',
  'MOBILE_FOLLOW_REPLY',
  'MOBILE_FOLLOW_FEEDBACK',
  'MOBILE_FOLLOW_REVIEW',
  'MOBILE_FOLLOW_RATING',
  'MOBILE_FOLLOW_SCORE',
  'MOBILE_FOLLOW_GRADE',
  'MOBILE_FOLLOW_EVALUATION',
  'MOBILE_FOLLOW_ASSESSMENT',
  'MOBILE_FOLLOW_ANALYSIS',
  'MOBILE_FOLLOW_RESEARCH',
  'MOBILE_FOLLOW_STUDY',
  'MOBILE_FOLLOW_INVESTIGATION',
  'MOBILE_FOLLOW_EXPLORATION',
  'MOBILE_FOLLOW_DISCOVERY',
  'MOBILE_FOLLOW_FINDING',
  'MOBILE_FOLLOW_RESULT',
  'MOBILE_FOLLOW_OUTCOME',
  'MOBILE_FOLLOW_CONCLUSION',
  'MOBILE_FOLLOW_SUMMARY',
  'MOBILE_FOLLOW_OVERVIEW',
  'MOBILE_FOLLOW_INTRODUCTION',
  'MOBILE_FOLLOW_DESCRIPTION',
  'MOBILE_FOLLOW_EXPLANATION',
  'MOBILE_FOLLOW_DEFINITION',
  'MOBILE_FOLLOW_MEANING',
  'MOBILE_FOLLOW_INTERPRETATION',
  'MOBILE_FOLLOW_UNDERSTANDING',
  'MOBILE_FOLLOW_COMPREHENSION',
  'MOBILE_FOLLOW_KNOWLEDGE',
  'MOBILE_FOLLOW_INFORMATION',
  'MOBILE_FOLLOW_DATA',
  'MOBILE_FOLLOW_DETAILS',
  'MOBILE_FOLLOW_FACTS',
  'MOBILE_FOLLOW_STATISTICS',
  'MOBILE_FOLLOW_NUMBERS',
  'MOBILE_FOLLOW_FIGURES',
  'MOBILE_FOLLOW_METRICS',
  'MOBILE_FOLLOW_MEASUREMENTS',
  'MOBILE_FOLLOW_DIMENSIONS',
  'MOBILE_FOLLOW_SPECIFICATIONS',
  'MOBILE_FOLLOW_REQUIREMENTS',
  'MOBILE_FOLLOW_CRITERIA',
  'MOBILE_FOLLOW_STANDARDS',
  'MOBILE_FOLLOW_GUIDELINES',
  'MOBILE_FOLLOW_RULES',
  'MOBILE_FOLLOW_REGULATIONS',
  'MOBILE_FOLLOW_POLICIES',
  'MOBILE_FOLLOW_PROCEDURES',
  'MOBILE_FOLLOW_PROTOCOLS',
  'MOBILE_FOLLOW_PROCESSES',
  'MOBILE_FOLLOW_METHODS',
  'MOBILE_FOLLOW_TECHNIQUES',
  'MOBILE_FOLLOW_APPROACHES',
  'MOBILE_FOLLOW_STRATEGIES',
  'MOBILE_FOLLOW_TACTICS',
  'MOBILE_FOLLOW_PLANS',
  'MOBILE_FOLLOW_SCHEMES',
  'MOBILE_FOLLOW_PROGRAMS',
  'MOBILE_FOLLOW_PROJECTS',
  'MOBILE_FOLLOW_INITIATIVES',
  'MOBILE_FOLLOW_CAMPAIGNS',
  'MOBILE_FOLLOW_EFFORTS',
  'MOBILE_FOLLOW_ACTIONS',
  'MOBILE_FOLLOW_ACTIVITIES',
  'MOBILE_FOLLOW_TASKS',
  'MOBILE_FOLLOW_JOBS',
  'MOBILE_FOLLOW_WORK',
  'MOBILE_FOLLOW_LABOR',
  'MOBILE_FOLLOW_EFFORT',
  'MOBILE_FOLLOW_ENERGY',
  'MOBILE_FOLLOW_POWER',
  'MOBILE_FOLLOW_STRENGTH',
  'MOBILE_FOLLOW_FORCE',
  'MOBILE_FOLLOW_PRESSURE',
  'MOBILE_FOLLOW_IMPACT',
  'MOBILE_FOLLOW_INFLUENCE',
  'MOBILE_FOLLOW_EFFECT',
  'MOBILE_FOLLOW_RESULT',
  'MOBILE_FOLLOW_CONSEQUENCE',
  'MOBILE_FOLLOW_OUTCOME',
  'MOBILE_FOLLOW_PRODUCT',
  'MOBILE_FOLLOW_OUTPUT',
  'MOBILE_FOLLOW_CREATION',
  'MOBILE_FOLLOW_PRODUCTION',
  'MOBILE_FOLLOW_MANUFACTURING',
  'MOBILE_FOLLOW_CONSTRUCTION',
  'MOBILE_FOLLOW_BUILDING',
  'MOBILE_FOLLOW_DEVELOPMENT',
  'MOBILE_FOLLOW_GROWTH',
  'MOBILE_FOLLOW_EXPANSION',
  'MOBILE_FOLLOW_IMPROVEMENT',
  'MOBILE_FOLLOW_ENHANCEMENT',
  'MOBILE_FOLLOW_UPGRADE',
  'MOBILE_FOLLOW_UPDATE',
  'MOBILE_FOLLOW_REVISION',
  'MOBILE_FOLLOW_MODIFICATION',
  'MOBILE_FOLLOW_CHANGE',
  'MOBILE_FOLLOW_TRANSFORMATION',
  'MOBILE_FOLLOW_EVOLUTION',
  'MOBILE_FOLLOW_PROGRESS',
  'MOBILE_FOLLOW_ADVANCEMENT',
  'MOBILE_FOLLOW_ACHIEVEMENT',
  'MOBILE_FOLLOW_ACCOMPLISHMENT',
  'MOBILE_FOLLOW_SUCCESS',
  'MOBILE_FOLLOW_VICTORY',
  'MOBILE_FOLLOW_WIN',
  'MOBILE_FOLLOW_TRIUMPH',
  'MOBILE_FOLLOW_CONQUEST',
  'MOBILE_FOLLOW_DEFEAT',
  'MOBILE_FOLLOW_LOSS',
  'MOBILE_FOLLOW_FAILURE',
  'MOBILE_FOLLOW_MISTAKE',
  'MOBILE_FOLLOW_ERROR',
  'MOBILE_FOLLOW_PROBLEM',
  'MOBILE_FOLLOW_ISSUE',
  'MOBILE_FOLLOW_CHALLENGE',
  'MOBILE_FOLLOW_DIFFICULTY',
  'MOBILE_FOLLOW_OBSTACLE',
  'MOBILE_FOLLOW_BARRIER',
  'MOBILE_FOLLOW_IMPEDIMENT',
  'MOBILE_FOLLOW_HINDRANCE',
  'MOBILE_FOLLOW_LIMITATION',
  'MOBILE_FOLLOW_RESTRICTION',
  'MOBILE_FOLLOW_CONSTRAINT',
  'MOBILE_FOLLOW_BOUNDARY',
  'MOBILE_FOLLOW_LIMIT',
  'MOBILE_FOLLOW_EDGE',
  'MOBILE_FOLLOW_BORDER',
  'MOBILE_FOLLOW_FRONTIER',
  'MOBILE_FOLLOW_HORIZON',
  'MOBILE_FOLLOW_FUTURE',
  'MOBILE_FOLLOW_TOMORROW',
  'MOBILE_FOLLOW_NEXT',
  'MOBILE_FOLLOW_UPCOMING',
  'MOBILE_FOLLOW_COMING',
  'MOBILE_FOLLOW_APPROACHING',
  'MOBILE_FOLLOW_ARRIVING',
  'MOBILE_FOLLOW_REACHING',
  'MOBILE_FOLLOW_ATTAINING',
  'MOBILE_FOLLOW_ACHIEVING',
  'MOBILE_FOLLOW_ACCOMPLISHING',
  'MOBILE_FOLLOW_COMPLETING',
  'MOBILE_FOLLOW_FINISHING',
  'MOBILE_FOLLOW_ENDING',
  'MOBILE_FOLLOW_CONCLUDING',
  'MOBILE_FOLLOW_CLOSING',
  'MOBILE_FOLLOW_TERMINATING',
  'MOBILE_FOLLOW_STOPPING',
  'MOBILE_FOLLOW_HALTING',
  'MOBILE_FOLLOW_PAUSING',
  'MOBILE_FOLLOW_WAITING',
  'MOBILE_FOLLOW_DELAYING',
  'MOBILE_FOLLOW_POSTPONING',
  'MOBILE_FOLLOW_DEFERRING',
  'MOBILE_FOLLOW_PUTTING_OFF',
  'MOBILE_FOLLOW_HOLDING_OFF',
  'MOBILE_FOLLOW_BACKING_OFF',
  'MOBILE_FOLLOW_STEPPING_BACK',
  'MOBILE_FOLLOW_WITHDRAWING',
  'MOBILE_FOLLOW_RETREATING',
  'MOBILE_FOLLOW_RETIRING',
  'MOBILE_FOLLOW_LEAVING',
  'MOBILE_FOLLOW_DEPARTING',
  'MOBILE_FOLLOW_EXITING',
  'MOBILE_FOLLOW_QUITTING',
  'MOBILE_FOLLOW_RESIGNING',
  'MOBILE_FOLLOW_GIVING_UP',
  'MOBILE_FOLLOW_SURRENDERING',
  'MOBILE_FOLLOW_YIELDING',
  'MOBILE_FOLLOW_SUBMITTING',
  'MOBILE_FOLLOW_COMPLYING',
  'MOBILE_FOLLOW_CONFORMING',
  'MOBILE_FOLLOW_ADHERING',
  'MOBILE_FOLLOW_FOLLOWING',
  'MOBILE_FOLLOW_PURSUING',
  'MOBILE_FOLLOW_CHASING',
  'MOBILE_FOLLOW_HUNTING',
  'MOBILE_FOLLOW_SEEKING',
  'MOBILE_FOLLOW_SEARCHING',
  'MOBILE_FOLLOW_LOOKING',
  'MOBILE_FOLLOW_FINDING',
  'MOBILE_FOLLOW_DISCOVERING',
  'MOBILE_FOLLOW_UNCOVERING',
  'MOBILE_FOLLOW_REVEALING',
  'MOBILE_FOLLOW_EXPOSING',
  'MOBILE_FOLLOW_SHOWING',
  'MOBILE_FOLLOW_DISPLAYING',
  'MOBILE_FOLLOW_PRESENTING',
  'MOBILE_FOLLOW_DEMONSTRATING',
  'MOBILE_FOLLOW_ILLUSTRATING',
  'MOBILE_FOLLOW_EXPLAINING',
  'MOBILE_FOLLOW_DESCRIBING',
  'MOBILE_FOLLOW_DETAILING',
  'MOBILE_FOLLOW_OUTLINING',
  'MOBILE_FOLLOW_SKETCHING',
  'MOBILE_FOLLOW_DRAWING',
  'MOBILE_FOLLOW_PAINTING',
  'MOBILE_FOLLOW_CREATING',
  'MOBILE_FOLLOW_MAKING',
  'MOBILE_FOLLOW_BUILDING',
  'MOBILE_FOLLOW_CONSTRUCTING',
  'MOBILE_FOLLOW_FORMING',
  'MOBILE_FOLLOW_SHAPING',
  'MOBILE_FOLLOW_MOLDING',
  'MOBILE_FOLLOW_SCULPTING',
  'MOBILE_FOLLOW_CARVING',
  'MOBILE_FOLLOW_CUTTING',
  'MOBILE_FOLLOW_SLICING',
  'MOBILE_FOLLOW_CHOPPING',
  'MOBILE_FOLLOW_DICING',
  'MOBILE_FOLLOW_MINCING',
  'MOBILE_FOLLOW_GRINDING',
  'MOBILE_FOLLOW_CRUSHING',
  'MOBILE_FOLLOW_BREAKING',
  'MOBILE_FOLLOW_SMASHING',
  'MOBILE_FOLLOW_DESTROYING',
  'MOBILE_FOLLOW_RUINING',
  'MOBILE_FOLLOW_DAMAGING',
  'MOBILE_FOLLOW_HARMING',
  'MOBILE_FOLLOW_HURTING',
  'MOBILE_FOLLOW_INJURING',
  'MOBILE_FOLLOW_WOUNDING',
  'MOBILE_FOLLOW_HEALING',
  'MOBILE_FOLLOW_CURING',
  'MOBILE_FOLLOW_TREATING',
  'MOBILE_FOLLOW_HELPING',
  'MOBILE_FOLLOW_ASSISTING',
  'MOBILE_FOLLOW_SUPPORTING',
  'MOBILE_FOLLOW_BACKING',
  'MOBILE_FOLLOW_ENDORSING',
  'MOBILE_FOLLOW_APPROVING',
  'MOBILE_FOLLOW_ACCEPTING',
  'MOBILE_FOLLOW_AGREEING',
  'MOBILE_FOLLOW_CONSENTING',
  'MOBILE_FOLLOW_PERMITTING',
  'MOBILE_FOLLOW_ALLOWING',
  'MOBILE_FOLLOW_ENABLING',
  'MOBILE_FOLLOW_FACILITATING',
  'MOBILE_FOLLOW_ENCOURAGING',
  'MOBILE_FOLLOW_MOTIVATING',
  'MOBILE_FOLLOW_INSPIRING',
  'MOBILE_FOLLOW_UPLIFTING',
  'MOBILE_FOLLOW_ELEVATING',
  'MOBILE_FOLLOW_RAISING',
  'MOBILE_FOLLOW_LIFTING',
  'MOBILE_FOLLOW_BOOSTING',
  'MOBILE_FOLLOW_INCREASING',
  'MOBILE_FOLLOW_GROWING',
  'MOBILE_FOLLOW_EXPANDING',
  'MOBILE_FOLLOW_EXTENDING',
  'MOBILE_FOLLOW_STRETCHING',
  'MOBILE_FOLLOW_REACHING',
  'MOBILE_FOLLOW_TOUCHING',
  'MOBILE_FOLLOW_FEELING',
  'MOBILE_FOLLOW_SENSING',
  'MOBILE_FOLLOW_PERCEIVING',
  'MOBILE_FOLLOW_RECOGNIZING',
  'MOBILE_FOLLOW_IDENTIFYING',
  'MOBILE_FOLLOW_DISTINGUISHING',
  'MOBILE_FOLLOW_DIFFERENTIATING',
  'MOBILE_FOLLOW_SEPARATING',
  'MOBILE_FOLLOW_DIVIDING',
  'MOBILE_FOLLOW_SPLITTING',
  'MOBILE_FOLLOW_PARTING',
  'MOBILE_FOLLOW_BREAKING_UP',
  'MOBILE_FOLLOW_DISSOLVING',
  'MOBILE_FOLLOW_MELTING',
  'MOBILE_FOLLOW_FREEZING',
  'MOBILE_FOLLOW_COOLING',
  'MOBILE_FOLLOW_HEATING',
  'MOBILE_FOLLOW_WARMING',
  'MOBILE_FOLLOW_BURNING',
  'MOBILE_FOLLOW_IGNITING',
  'MOBILE_FOLLOW_LIGHTING',
  'MOBILE_FOLLOW_ILLUMINATING',
  'MOBILE_FOLLOW_BRIGHTENING',
  'MOBILE_FOLLOW_DARKENING',
  'MOBILE_FOLLOW_SHADOWING',
  'MOBILE_FOLLOW_HIDING',
  'MOBILE_FOLLOW_CONCEALING',
  'MOBILE_FOLLOW_COVERING',
  'MOBILE_FOLLOW_WRAPPING',
  'MOBILE_FOLLOW_PACKAGING',
  'MOBILE_FOLLOW_BOXING',
  'MOBILE_FOLLOW_SHIPPING',
  'MOBILE_FOLLOW_DELIVERING',
  'MOBILE_FOLLOW_TRANSPORTING',
  'MOBILE_FOLLOW_CARRYING',
  'MOBILE_FOLLOW_MOVING',
  'MOBILE_FOLLOW_SHIFTING',
  'MOBILE_FOLLOW_CHANGING',
  'MOBILE_FOLLOW_TRANSFORMING',
  'MOBILE_FOLLOW_CONVERTING',
  'MOBILE_FOLLOW_SWITCHING',
  'MOBILE_FOLLOW_TURNING',
  'MOBILE_FOLLOW_ROTATING',
  'MOBILE_FOLLOW_SPINNING',
  'MOBILE_FOLLOW_TWISTING',
  'MOBILE_FOLLOW_BENDING',
  'MOBILE_FOLLOW_CURVING',
  'MOBILE_FOLLOW_ARCHING',
  'MOBILE_FOLLOW_LOOPING',
  'MOBILE_FOLLOW_CIRCLING',
  'MOBILE_FOLLOW_ORBITING',
  'MOBILE_FOLLOW_REVOLVING',
  'MOBILE_FOLLOW_CYCLING',
  'MOBILE_FOLLOW_REPEATING',
  'MOBILE_FOLLOW_RECURRING',
  'MOBILE_FOLLOW_RETURNING',
  'MOBILE_FOLLOW_COMING_BACK',
  'MOBILE_FOLLOW_GOING_BACK',
  'MOBILE_FOLLOW_BACKING_UP',
  'MOBILE_FOLLOW_REVERSING',
  'MOBILE_FOLLOW_UNDOING',
  'MOBILE_FOLLOW_CANCELING',
  'MOBILE_FOLLOW_NEGATING',
  'MOBILE_FOLLOW_DENYING',
  'MOBILE_FOLLOW_REFUSING',
  'MOBILE_FOLLOW_REJECTING',
  'MOBILE_FOLLOW_DECLINING',
  'MOBILE_FOLLOW_DISMISSING',
  'MOBILE_FOLLOW_IGNORING',
  'MOBILE_FOLLOW_OVERLOOKING',
  'MOBILE_FOLLOW_DISREGARDING',
  'MOBILE_FOLLOW_NEGLECTING',
  'MOBILE_FOLLOW_ABANDONING',
  'MOBILE_FOLLOW_DESERTING',
  'MOBILE_FOLLOW_FORSAKING',
  'MOBILE_FOLLOW_LEAVING_BEHIND',
  'MOBILE_FOLLOW_MOVING_ON',
  'MOBILE_FOLLOW_PROGRESSING',
  'MOBILE_FOLLOW_ADVANCING',
  'MOBILE_FOLLOW_PROCEEDING',
  'MOBILE_FOLLOW_CONTINUING',
  'MOBILE_FOLLOW_PERSISTING',
  'MOBILE_FOLLOW_PERSEVERING',
  'MOBILE_FOLLOW_ENDURING',
  'MOBILE_FOLLOW_LASTING',
  'MOBILE_FOLLOW_SURVIVING',
  'MOBILE_FOLLOW_LIVING',
  'MOBILE_FOLLOW_EXISTING',
  'MOBILE_FOLLOW_BEING',
  'MOBILE_FOLLOW_STAYING',
  'MOBILE_FOLLOW_REMAINING',
  'MOBILE_FOLLOW_KEEPING',
  'MOBILE_FOLLOW_HOLDING',
  'MOBILE_FOLLOW_GRASPING',
  'MOBILE_FOLLOW_GRIPPING',
  'MOBILE_FOLLOW_CLUTCHING',
  'MOBILE_FOLLOW_SEIZING',
  'MOBILE_FOLLOW_GRABBING',
  'MOBILE_FOLLOW_TAKING',
  'MOBILE_FOLLOW_GETTING',
  'MOBILE_FOLLOW_OBTAINING',
  'MOBILE_FOLLOW_ACQUIRING',
  'MOBILE_FOLLOW_GAINING',
  'MOBILE_FOLLOW_EARNING',
  'MOBILE_FOLLOW_WINNING',
  'MOBILE_FOLLOW_SUCCEEDING',
  'MOBILE_FOLLOW_ACHIEVING',
  'MOBILE_FOLLOW_ACCOMPLISHING',
  'MOBILE_FOLLOW_COMPLETING',
  'MOBILE_FOLLOW_FINISHING',
  'MOBILE_FOLLOW_ENDING',
  'MOBILE_FOLLOW_CONCLUDING',
  'MOBILE_FOLLOW_CLOSING',
  'MOBILE_FOLLOW_SHUTTING',
  'MOBILE_FOLLOW_LOCKING',
  'MOBILE_FOLLOW_SECURING',
  'MOBILE_FOLLOW_PROTECTING',
  'MOBILE_FOLLOW_GUARDING',
  'MOBILE_FOLLOW_DEFENDING',
  'MOBILE_FOLLOW_SHIELDING',
  'MOBILE_FOLLOW_COVERING',
  'MOBILE_FOLLOW_SHELTERING',
  'MOBILE_FOLLOW_HOUSING',
  'MOBILE_FOLLOW_ACCOMMODATING',
  'MOBILE_FOLLOW_HOSTING',
  'MOBILE_FOLLOW_WELCOMING',
  'MOBILE_FOLLOW_GREETING',
  'MOBILE_FOLLOW_MEETING',
  'MOBILE_FOLLOW_ENCOUNTERING',
  'MOBILE_FOLLOW_FACING',
  'MOBILE_FOLLOW_CONFRONTING',
  'MOBILE_FOLLOW_CHALLENGING',
  'MOBILE_FOLLOW_QUESTIONING',
  'MOBILE_FOLLOW_ASKING',
  'MOBILE_FOLLOW_INQUIRING',
  'MOBILE_FOLLOW_INVESTIGATING',
  'MOBILE_FOLLOW_EXPLORING',
  'MOBILE_FOLLOW_DISCOVERING',
  'MOBILE_FOLLOW_FINDING',
  'MOBILE_FOLLOW_LOCATING',
  'MOBILE_FOLLOW_POSITIONING',
  'MOBILE_FOLLOW_PLACING',
  'MOBILE_FOLLOW_PUTTING',
  'MOBILE_FOLLOW_SETTING',
  'MOBILE_FOLLOW_ARRANGING',
  'MOBILE_FOLLOW_ORGANIZING',
  'MOBILE_FOLLOW_SORTING',
  'MOBILE_FOLLOW_ORDERING',
  'MOBILE_FOLLOW_RANKING',
  'MOBILE_FOLLOW_RATING',
  'MOBILE_FOLLOW_SCORING',
  'MOBILE_FOLLOW_GRADING',
  'MOBILE_FOLLOW_EVALUATING',
  'MOBILE_FOLLOW_ASSESSING',
  'MOBILE_FOLLOW_MEASURING',
  'MOBILE_FOLLOW_CALCULATING',
  'MOBILE_FOLLOW_COMPUTING',
  'MOBILE_FOLLOW_PROCESSING',
  'MOBILE_FOLLOW_ANALYZING',
  'MOBILE_FOLLOW_EXAMINING',
  'MOBILE_FOLLOW_INSPECTING',
  'MOBILE_FOLLOW_CHECKING',
  'MOBILE_FOLLOW_TESTING',
  'MOBILE_FOLLOW_TRYING',
  'MOBILE_FOLLOW_ATTEMPTING',
  'MOBILE_FOLLOW_ENDEAVORING',
  'MOBILE_FOLLOW_STRIVING',
  'MOBILE_FOLLOW_WORKING',
  'MOBILE_FOLLOW_LABORING',
  'MOBILE_FOLLOW_TOILING',
  'MOBILE_FOLLOW_STRUGGLING',
  'MOBILE_FOLLOW_FIGHTING',
  'MOBILE_FOLLOW_BATTLING',
  'MOBILE_FOLLOW_COMPETING',
  'MOBILE_FOLLOW_CONTENDING',
  'MOBILE_FOLLOW_VYING',
  'MOBILE_FOLLOW_RACING',
  'MOBILE_FOLLOW_RUNNING',
  'MOBILE_FOLLOW_JOGGING',
  'MOBILE_FOLLOW_WALKING',
  'MOBILE_FOLLOW_STEPPING',
  'MOBILE_FOLLOW_MARCHING',
  'MOBILE_FOLLOW_HIKING',
  'MOBILE_FOLLOW_CLIMBING',
  'MOBILE_FOLLOW_ASCENDING',
  'MOBILE_FOLLOW_RISING',
  'MOBILE_FOLLOW_ELEVATING',
  'MOBILE_FOLLOW_LIFTING',
  'MOBILE_FOLLOW_RAISING',
  'MOBILE_FOLLOW_BOOSTING',
  'MOBILE_FOLLOW_INCREASING',
  'MOBILE_FOLLOW_GROWING',
  'MOBILE_FOLLOW_EXPANDING',
  'MOBILE_FOLLOW_EXTENDING',
  'MOBILE_FOLLOW_STRETCHING',
  'MOBILE_FOLLOW_REACHING',
  'MOBILE_FOLLOW_TOUCHING',
  'MOBILE_FOLLOW_FEELING',
  'MOBILE_FOLLOW_SENSING',
  'MOBILE_FOLLOW_PERCEIVING',
  'MOBILE_FOLLOW_RECOGNIZING',
  'MOBILE_FOLLOW_IDENTIFYING',
  'MOBILE_FOLLOW_DISTINGUISHING',
  'MOBILE_FOLLOW_DIFFERENTIATING',
  'MOBILE_FOLLOW_SEPARATING',
  'MOBILE_FOLLOW_DIVIDING',
  'MOBILE_FOLLOW_SPLITTING',
  'MOBILE_FOLLOW_PARTING',
  'MOBILE_FOLLOW_BREAKING_UP',
  'MOBILE_FOLLOW_DISSOLVING',
  'MOBILE_FOLLOW_MELTING',
  'MOBILE_FOLLOW_FREEZING',
  'MOBILE_FOLLOW_COOLING',
  'MOBILE_FOLLOW_HEATING',
  'MOBILE_FOLLOW_WARMING',
  'MOBILE_FOLLOW_BURNING',
  'MOBILE_FOLLOW_IGNITING',
  'MOBILE_FOLLOW_LIGHTING',
  'MOBILE_FOLLOW_ILLUMINATING',
  'MOBILE_FOLLOW_BRIGHTENING',
  'MOBILE_FOLLOW_DARKENING',
  'MOBILE_FOLLOW_SHADOWING',
  'MOBILE_FOLLOW_HIDING',
  'MOBILE_FOLLOW_CONCEALING',
  'MOBILE_FOLLOW_COVERING',
  'MOBILE_FOLLOW_WRAPPING',
  'MOBILE_FOLLOW_PACKAGING',
  'MOBILE_FOLLOW_BOXING',
  'MOBILE_FOLLOW_SHIPPING',
  'MOBILE_FOLLOW_DELIVERING',
  'MOBILE_FOLLOW_TRANSPORTING',
  'MOBILE_FOLLOW_CARRYING',
  'MOBILE_FOLLOW_MOVING',
  'MOBILE_FOLLOW_SHIFTING',
  'MOBILE_FOLLOW_CHANGING',
  'MOBILE_FOLLOW_TRANSFORMING',
  'MOBILE_FOLLOW_CONVERTING',
  'MOBILE_FOLLOW_SWITCHING',
  'MOBILE_FOLLOW_TURNING',
  'MOBILE_FOLLOW_ROTATING',
  'MOBILE_FOLLOW_SPINNING',
  'MOBILE_FOLLOW_TWISTING',
  'MOBILE_FOLLOW_BENDING',
  'MOBILE_FOLLOW_CURVING',
  'MOBILE_FOLLOW_ARCHING',
  'MOBILE_FOLLOW_LOOPING',
  'MOBILE_FOLLOW_CIRCLING',
  'MOBILE_FOLLOW_ORBITING',
  'MOBILE_FOLLOW_REVOLVING',
  'MOBILE_FOLLOW_CYCLING',
  'MOBILE_FOLLOW_REPEATING',
  'MOBILE_FOLLOW_RECURRING',
  'MOBILE_FOLLOW_RETURNING',
  'MOBILE_FOLLOW_COMING_BACK',
  'MOBILE_FOLLOW_GOING_BACK',
  'MOBILE_FOLLOW_BACKING_UP',
  'MOBILE_FOLLOW_REVERSING',
  'MOBILE_FOLLOW_UNDOING',
  'MOBILE_FOLLOW_CANCELING',
  'MOBILE_FOLLOW_NEGATING',
  'MOBILE_FOLLOW_DENYING',
  'MOBILE_FOLLOW_REFUSING',
  'MOBILE_FOLLOW_REJECTING',
  'MOBILE_FOLLOW_DECLINING',
  'MOBILE_FOLLOW_DISMISSING',
  'MOBILE_FOLLOW_IGNORING',
  'MOBILE_FOLLOW_OVERLOOKING',
  'MOBILE_FOLLOW_DISREGARDING',
  'MOBILE_FOLLOW_NEGLECTING',
  'MOBILE_FOLLOW_ABANDONING',
  'MOBILE_FOLLOW_DESERTING',
  'MOBILE_FOLLOW_FORSAKING',
  'MOBILE_FOLLOW_LEAVING_BEHIND',
  'MOBILE_FOLLOW_MOVING_ON',
  'MOBILE_FOLLOW_PROGRESSING',
  'MOBILE_FOLLOW_ADVANCING',
  'MOBILE_FOLLOW_PROCEEDING',
  'MOBILE_FOLLOW_CONTINUING',
  'MOBILE_FOLLOW_PERSISTING',
  'MOBILE_FOLLOW_PERSEVERING',
  'MOBILE_FOLLOW_ENDURING',
  'MOBILE_FOLLOW_LASTING',
  'MOBILE_FOLLOW_SURVIVING',
  'MOBILE_FOLLOW_LIVING',
  'MOBILE_FOLLOW_EXISTING',
  'MOBILE_FOLLOW_BEING',
  'MOBILE_FOLLOW_STAYING',
  'MOBILE_FOLLOW_REMAINING',
  'MOBILE_FOLLOW_KEEPING',
  'MOBILE_FOLLOW_HOLDING',
  'MOBILE_FOLLOW_GRASPING',
  'MOBILE_FOLLOW_GRIPPING',
  'MOBILE_FOLLOW_CLUTCHING',
  'MOBILE_FOLLOW_SEIZING',
  'MOBILE_FOLLOW_GRABBING',
  'MOBILE_FOLLOW_TAKING',
  'MOBILE_FOLLOW_GETTING',
  'MOBILE_FOLLOW_OBTAINING',
  'MOBILE_FOLLOW_ACQUIRING',
  'MOBILE_FOLLOW_GAINING',
  'MOBILE_FOLLOW_EARNING',
  'MOBILE_FOLLOW_WINNING',
  'MOBILE_FOLLOW_SUCCEEDING',
  'MOBILE_FOLLOW_ACHIEVING',
  'MOBILE_FOLLOW_ACCOMPLISHING',
  'MOBILE_FOLLOW_COMPLETING',
  'MOBILE_FOLLOW_FINISHING',
  'MOBILE_FOLLOW_ENDING'
] as const;

// Ad Format Types
export const AD_FORMAT_TYPES = [
  'DESKTOP_FEED_STANDARD',
  'MOBILE_FEED_STANDARD',
  'RIGHT_COLUMN_STANDARD',
  'MOBILE_FULLWIDTH',
  'MOBILE_NATIVE',
  'DESKTOP_SIDEBAR_STANDARD',
  'MOBILE_MEDIUM_RECTANGLE',
  'MOBILE_BANNER',
  'DESKTOP_FEED_STANDARD_CAROUSEL',
  'MOBILE_FEED_STANDARD_CAROUSEL',
  'INSTAGRAM_STANDARD',
  'INSTAGRAM_STORY',
  'MESSENGER_MOBILE_INBOX_MEDIA',
  'MESSENGER_MOBILE_STORY_MEDIA',
  'MESSENGER_DESKTOP_INBOX_MEDIA',
  'MESSENGER_MOBILE_INBOX_MEDIA_RICH',
  'MESSENGER_MOBILE_STORY_MEDIA_RICH',
  'MESSENGER_DESKTOP_INBOX_MEDIA_RICH',
  'AUDIENCE_NETWORK_OUTSTREAM_VIDEO',
  'AUDIENCE_NETWORK_BANNER',
  'AUDIENCE_NETWORK_INTERSTITIAL',
  'AUDIENCE_NETWORK_NATIVE',
  'AUDIENCE_NETWORK_NATIVE_BANNER',
  'AUDIENCE_NETWORK_REWARDED_VIDEO',
  'AUDIENCE_NETWORK_INSTREAM_VIDEO',
  'INSTANT_ARTICLE_STANDARD',
  'INSTANT_ARTICLE_RECIRCULATION_AD',
  'INSTREAM_VIDEO_DESKTOP',
  'INSTREAM_VIDEO_MOBILE',
  'SUGGESTED_VIDEO_DESKTOP',
  'SUGGESTED_VIDEO_MOBILE',
  'MARKETPLACE_MOBILE',
  'FACEBOOK_STORY_MOBILE',
  'FACEBOOK_STORY_STICKER_MOBILE',
  'FACEBOOK_FEED_DESKTOP',
  'FACEBOOK_FEED_MOBILE',
  'FACEBOOK_RIGHT_COLUMN_DESKTOP',
  'FACEBOOK_MARKETPLACE_MOBILE',
  'FACEBOOK_VIDEO_FEEDS_MOBILE',
  'FACEBOOK_VIDEO_FEEDS_DESKTOP',
  'FACEBOOK_STORY_DESKTOP',
  'FACEBOOK_SEARCH_RESULTS_DESKTOP',
  'FACEBOOK_SEARCH_RESULTS_MOBILE',
  'FACEBOOK_GROUPS_FEED_DESKTOP',
  'FACEBOOK_GROUPS_FEED_MOBILE',
  'FACEBOOK_BUSINESS_DISCOVERY_MOBILE',
  'FACEBOOK_REELS_MOBILE',
  'FACEBOOK_REELS_DESKTOP',
  'WATCH_FEED_MOBILE',
  'WATCH_FEED_DESKTOP',
  'INSTAGRAM_STANDARD_CAROUSEL',
  'INSTAGRAM_STORY_CAROUSEL',
  'INSTAGRAM_REELS',
  'INSTAGRAM_EXPLORE',
  'INSTAGRAM_EXPLORE_GRID_HOME',
  'INSTAGRAM_EXPLORE_CONTEXTUAL',
  'INSTAGRAM_REELS_OVERLAY',
  'INSTAGRAM_SEARCH_RESULTS',
  'INSTAGRAM_PROFILE_REELS',
  'INSTAGRAM_PROFILE_FEED',
  'INSTAGRAM_SHOP',
  'THREADS_MOBILE',
  'THREADS_DESKTOP'
] as const;

// Status Types
export const CREATIVE_STATUS_TYPES = [
  'ACTIVE',
  'PAUSED',
  'DELETED',
  'PENDING_REVIEW',
  'DISAPPROVED',
  'PREAPPROVED'
] as const;

// Authorization Categories
export const AUTHORIZATION_CATEGORIES = [
  'NONE',
  'POLITICAL',
  'ISSUE_ELECTIONS_POLITICS',
  'HOUSING',
  'EMPLOYMENT',
  'CREDIT'
] as const;

// Applink Treatment Types
export const APPLINK_TREATMENT_TYPES = [
  'deeplink_with_web_fallback',
  'deeplink_with_appstore_fallback',
  'web_only'
] as const;

// Dynamic Ad Voice Types
export const DYNAMIC_AD_VOICE_TYPES = [
  'DYNAMIC_VOICE_STANDARD',
  'DYNAMIC_VOICE_PROMOTIONAL',
  'DYNAMIC_VOICE_AUTHORITATIVE',
  'DYNAMIC_VOICE_CASUAL',
  'DYNAMIC_VOICE_PLAYFUL',
  'DYNAMIC_VOICE_PROFESSIONAL',
  'DYNAMIC_VOICE_URGENT',
  'DYNAMIC_VOICE_FRIENDLY',
  'DYNAMIC_VOICE_INFORMATIVE',
  'DYNAMIC_VOICE_TECHNICAL'
] as const;
